### ISSUE TITLE
Add CAN-logging for x2 devices

### ISSUE THREAD

**Issue by Guenni9** [DeerMaximum/Technische-Alternative-CMI#10]
Would be useful, to read also `La, Ld` parameters in the JSON-API.

So, not only inputs and outputs were readable, but every data configured in CAN-logging could be retrieved.
Example could be the actual power from sun collector, a computed temperature, like "VL Soll" and so on.
Only CAN logging in TAPPS needs to be configured. 

Actually, using [Node-RED](https://github.com/PeterAustria/node-red-contrib-ta-cmi) could be used as workaround, to transfer the data to Home Assistant.

Here an example call:
`http://192.168.0.13/INCLUDE/api.cgi?jsonnode=3&jsonparam=La,Ld`
Here the output:
`{ "Header":{ "Version":6, "Device":"91", "Timestamp":1667124402 }, "Data":{ "Logging Analog":[ { "Number":1, "AD":"A", "Value":{ "Value":49.0, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":34.3, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":35.3, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":34.4, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":21.1, "Unit":"1" } }, { "Number":6, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }], "Logging Digital":[ { "Number":1, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":3, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":4, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":7, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":8, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":9, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":10, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }]}, "Status":"OK", "Status code":0 }`

**Comment by DeerMaximum** [comment]
CAN logging is available in the 1.1.0-beta. If you want you can try it out.
