### ISSUE TITLE
Nach Update 1.9.5 keine Sensoren mehr

### ISSUE THREAD

**Issue by sholvatealc** [DeerMaximum/Technische-Alternative-CMI#108]
Nach Update von Version 1.9.4 auf 1.9.5 Haben die Sensoren keinen Inhalt mehr.
Core: 2024.12.3
Supervisior: 2024.11.4

**Comment by DeerMaximum** [comment]
The bug is fixed in version 1.9.6

**Comment by sholvatealc** [comment]
Danke. 1.9.6 funktioniert
