### ISSUE TITLE
Failure during the CAN-request/parameter not available 

### ISSUE THREAD

**Issue by Binda5000** [DeerMaximum/Technische-Alternative-CMI#15]
Hello, thanks for this great project.

I have an issue adding more than one Device.
I can add node 1 and data is coming in, but I would also need data from Node 32.

![Screenshot_20221107-193552_Home Assistant](https://user-images.githubusercontent.com/77990308/200389425-cf1f2feb-5199-4a9a-a5ae-c1852ce356fa.jpg)

Log Message:
![Screenshot_20221107-193605_Home Assistant](https://user-images.githubusercontent.com/77990308/200389541-066ee1a3-5010-4d8b-a597-5910860156f3.jpg)

My Can Bus configuration:
![Screenshot_20221107-193625_Chrome](https://user-images.githubusercontent.com/77990308/200389613-4455e129-d009-4980-a372-23d6859384cb.jpg)

Best Regards,
Christoph

**Comment by DeerMaximum** [comment]
Does the error occur every time you try to set up the integration? Because normally the error does not occur again with a new attempt. 

_Gesendet von meinem Pixel 4A (5G) mit [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by Alex1976de** [comment]
Yes, i did it already a few times and always the same issue

**Comment by Binda5000** [comment]
Hello,

I just retried the setup process, now I get an unknown error and no message in the Logs.


![Screenshot_20221108-103139_Home Assistant.jpg](https://user-images.githubusercontent.com/77990308/200528936-a2779d2d-e8e6-4c85-9546-85e12c6d7d13.jpg)

Yesterday I had the issue described in my Previous Post every time I tried the setup.

**Comment by Binda5000** [comment]
Node 32

URL:

http://CMI_IP/INCLUDE/api.cgi?jsonnode=32&jsonparam=I,O

Response:

`{ "Header":{ "Version":6, "Device":"91", "Timestamp":1667947244 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":8.4, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":20.6, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":21.2, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":18.1, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":17.7, "Unit":"46", "RAS":"0" } }], "Outputs":[ { "Number":1, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":7, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }, { "Number":8, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }, { "Number":9, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }, { "Number":10, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }]}, "Status":"OK", "Status code":0 }`




Node 50:

URL:

http://CMI_IP/INCLUDE/api.cgi?jsonnode=50&jsonparam=I,O

RESPONSE:

```
{ "Header":{ "Version":6, "Device":"8C", "Timestamp":1667947384 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":18.5, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":55.9, "Unit":"8" } }, { "Number":3, "AD":"A", "Value":{ "Value":7.6, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":989.7, "Unit":"65" } }, { "Number":5, "AD":"A", "Value":{ "Value":0, "Unit":"67" } }, { "Number":6, "AD":"A", "Value":{ "Value":8.8, "Unit":"52" } }]}, "Status":"OK", "Status code":0 }
```

**Comment by DeerMaximum** [comment]
Can you disable CAN-Logging during setup and try again with that?

**Comment by Binda5000** [comment]
Same Error:


`Error while communicating with a device. See logs for details`

Logfile:

```
This error originated from a custom integration.

Logger: custom_components.ta_cmi
Source: custom_components/ta_cmi/config_flow.py:89
Integration: Technische Alternative C.M.I. (documentation, issues)
First occurred: 18:40:00 (3 occurrences)
Last logged: 18:42:02

Error while communicating with a device (32): Failure during the CAN-request/parameter not available for this device
Error while communicating with a device (48): Device not supported
Error while communicating with a device (50): Failure during the CAN-request/parameter not available for this device
```

**Comment by DeerMaximum** [comment]
Since the error still occurs I can't really help you. 

The problem is with the CMI/node, which as described in the error message either does not support the parameters given by the integration or the CAN-request failed.

That the parameters are not correct, we have concluded from the fact that you have made the requests manually and they have not failed. So the CAN-request fails, unfortunately I can't really do anything about that or find out why that is so.

The only way it could still work would be to enter the desired devices manually into the configuration, which has its own risks.


In case you want to try this, write me shortly.

**Comment by Binda5000** [comment]
I would love to try and input the configuration manually.
Where is the config file located?

**Comment by DeerMaximum** [comment]
The configuration file is in your HomeAssistant directory under `.storage/core.config_entries`.
I would **highly recommend** you to copy and save the file before editing it!

First you set up the integration with the working device to create the required configuration entry.

Now there should be a place in the file that looks something like this:
```json
        "entry_id": "12a06eca1fffe18d5ffdc5baad5422b1",
        "version": 1,
        "domain": "ta_cmi",
        "title": "C.M.I",
        "data": {
          "host": "http://IP",
          "username": "USERNAME",
          "password": "PASSWORD",
          "devices": [
            {
              "id": "2", 
              "fetchmode": "all",
              "type": "UVR16x2", 
              "channels": []
            }]
        }
```

Now insert this section under the already existing one and replace the ID with the one from one of the other nodes and the type with the matching device type (you have to remove the comments marked in red here):
```json
{
    "id": "2", //DEVICE ID
    "fetchmode": "all",
    "type": "UVR16x2", //DEVICE TYPE
    "channels": []
}
```

It will look something like this:

```json
        "entry_id": "12a06eca1fffe18d5ffdc5baad5422b1",
        "version": 1,
        "domain": "ta_cmi",
        "title": "C.M.I",
        "data": {
          "host": "http://IP",
          "username": "USERNAME",
          "password": "PASSWORD",
          "devices": [
            {
              "id": "2", 
              "fetchmode": "all",
              "type": "UVR16x2",
              "channels": []
            },
            {
                "id": "32", 
                "fetchmode": "all",
                "type": "UVR610", 
                "channels": []
            }
            ]
        }
```

Don't forget the comma between the curly brackets.

Now you have to save the file and restart Home Assistant.
If there is an error when starting, there is something wrong with the configuration, in this case just restore the saved file.

With a little luck the error will not occur anymore and the channels of the device will be displayed.

To add the last device repeat the insert step.

**Comment by Chris5020** [comment]
I've almost the same problem, for me it is device 40 EZ3

Also very strange: when I try to connect with HomeAssistant, the CMI Webinterface seems to crash and is not available for almost 1 minute, 
until I can connect again via loal web interface
But the direct json-calls still work

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ta_cmi
Source: custom_components/ta_cmi/config_flow.py:96
Integration: Technische Alternative C.M.I. (documentation, issues)
First occurred: 21:57:04 (2 occurrences)
Last logged: 21:58:34

Error while communicating with a device (40): Failure during the CAN-request/parameter not available for this device`

I would try manual configuration, but I'm not able to add the integration.

disable datalogging in settings (was CAN40 x2-tech) does not change anything.

Can you give me a hint, where I could start debugging in the script?
My python is not the best, but I'm able to read and adopt existing code

regards, christian

**Comment by DeerMaximum** [comment]
@Chris5020 
Is the CAN-EZ3 your only device that you can integrate? 
Does the error also occur with CAN logging switched off in the integration?

You said that the direct retrieval of the data via the API works and the error only occurs with the integration. With which jsonparam did you retrieve the data?

**Comment by Chris5020** [comment]
the EZ3 does not support I,O
when I use jsonparam=D it works
{ "Header":{ "Version":6, "Device":"8F", "Timestamp":1670960961 }, "Data":{ "DL-Bus":[ ]}, "Status":"OK", "Status code":0 }

**Comment by DeerMaximum** [comment]
If the EZ3 does not support inputs and outputs, what data do you want to read with the integration?

**Comment by Chris5020** [comment]
it supports DL for reading params like power in/out and such things
it also supports O,D or O or Sg
O = { "Header":{ "Version":6, "Device":"8F", "Timestamp":1671215716 }, "Data":{ }, "Status":"OK", "Status code":0 }
Sg = 
`{ "Header":{ "Version":6, "Device":"8F", "Timestamp":1671215745 }, "Data":{ "General":[ { "Number":1, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":3, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":5, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":7, "AD":"A", "Value":{ "Value":50.08, "Unit":"21" } }, { "Number":8, "AD":"A", "Value":{ "Value":40, "Unit":"0" } }, { "Number":9, "AD":"D", "Value":{ "Value":1, "Unit":"44" } }, { "Number":10, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":11, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":12, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":13, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }]}, "Status":"OK", "Status code":0 }`

St = 
`{ "Header":{ "Version":6, "Device":"8F", "Timestamp":1671215778 }, "Data":{ "Time":[ { "Number":1, "AD":"A", "Value":{ "Value":21, "Unit":"4" } }, { "Number":2, "AD":"A", "Value":{ "Value":37, "Unit":"5" } }, { "Number":3, "AD":"A", "Value":{ "Value":18, "Unit":"15" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":7, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":8, "AD":"A", "Value":{ "Value":1117, "Unit":"60" } }]}, "Status":"OK", "Status code":0 }`

**Comment by DeerMaximum** [comment]
@Chris5020 
Can you send me the response using these parameters?: D,Sg,Sd,St,Ss,Sp,AM,La,Ld

**Comment by Chris5020** [comment]
Good  morning, the result is
`{
    "Header": {
        "Version": 6,
        "Device": "8F",
        "Timestamp": 1672475855
    },
    "Data": {
        "DL-Bus": [],
        "General": [
            {
                "Number": 1,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            },
            {
                "Number": 2,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "44"
                }
            },
            {
                "Number": 3,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "44"
                }
            },
            {
                "Number": 4,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "44"
                }
            },
            {
                "Number": 5,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "44"
                }
            },
            {
                "Number": 6,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "44"
                }
            },
            {
                "Number": 7,
                "AD": "A",
                "Value": {
                    "Value": 50.07,
                    "Unit": "21"
                }
            },
            {
                "Number": 8,
                "AD": "A",
                "Value": {
                    "Value": 40,
                    "Unit": "0"
                }
            },
            {
                "Number": 9,
                "AD": "D",
                "Value": {
                    "Value": 1,
                    "Unit": "44"
                }
            },
            {
                "Number": 10,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            },
            {
                "Number": 11,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            },
            {
                "Number": 12,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            },
            {
                "Number": 13,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            }
        ],
        "Date": [
            {
                "Number": 1,
                "AD": "A",
                "Value": {
                    "Value": 31,
                    "Unit": "0"
                }
            },
            {
                "Number": 2,
                "AD": "A",
                "Value": {
                    "Value": 12,
                    "Unit": "0"
                }
            },
            {
                "Number": 3,
                "AD": "A",
                "Value": {
                    "Value": 22,
                    "Unit": "0"
                }
            },
            {
                "Number": 4,
                "AD": "A",
                "Value": {
                    "Value": 6,
                    "Unit": "0"
                }
            },
            {
                "Number": 5,
                "AD": "A",
                "Value": {
                    "Value": 52,
                    "Unit": "0"
                }
            },
            {
                "Number": 6,
                "AD": "A",
                "Value": {
                    "Value": 365,
                    "Unit": "0"
                }
            },
            {
                "Number": 7,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            },
            {
                "Number": 8,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            },
            {
                "Number": 9,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            },
            {
                "Number": 10,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            }
        ],
        "Time": [
            {
                "Number": 1,
                "AD": "A",
                "Value": {
                    "Value": 3,
                    "Unit": "4"
                }
            },
            {
                "Number": 2,
                "AD": "A",
                "Value": {
                    "Value": 39,
                    "Unit": "5"
                }
            },
            {
                "Number": 3,
                "AD": "A",
                "Value": {
                    "Value": 8,
                    "Unit": "15"
                }
            },
            {
                "Number": 4,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            },
            {
                "Number": 5,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            },
            {
                "Number": 6,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "43"
                }
            },
            {
                "Number": 7,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "44"
                }
            },
            {
                "Number": 8,
                "AD": "A",
                "Value": {
                    "Value": 519,
                    "Unit": "60"
                }
            }
        ],
        "Sun": [
            {
                "Number": 1,
                "AD": "A",
                "Value": {
                    "Value": 474,
                    "Unit": "60"
                }
            },
            {
                "Number": 2,
                "AD": "A",
                "Value": {
                    "Value": 970,
                    "Unit": "60"
                }
            },
            {
                "Number": 3,
                "AD": "A",
                "Value": {
                    "Value": 0,
                    "Unit": "5"
                }
            },
            {
                "Number": 4,
                "AD": "A",
                "Value": {
                    "Value": 45,
                    "Unit": "5"
                }
            },
            {
                "Number": 5,
                "AD": "A",
                "Value": {
                    "Value": 451,
                    "Unit": "5"
                }
            },
            {
                "Number": 6,
                "AD": "A",
                "Value": {
                    "Value": 0,
                    "Unit": "5"
                }
            },
            {
                "Number": 7,
                "AD": "A",
                "Value": {
                    "Value": 5.3,
                    "Unit": "54"
                }
            },
            {
                "Number": 8,
                "AD": "A",
                "Value": {
                    "Value": 134.4,
                    "Unit": "54"
                }
            },
            {
                "Number": 9,
                "AD": "D",
                "Value": {
                    "Value": 1,
                    "Unit": "44"
                }
            },
            {
                "Number": 10,
                "AD": "A",
                "Value": {
                    "Value": 722,
                    "Unit": "60"
                }
            }
        ],
        "Electrical power": [
            {
                "Number": 1,
                "AD": "A",
                "Value": {
                    "Value": 1106,
                    "Unit": "69"
                }
            },
            {
                "Number": 2,
                "AD": "A",
                "Value": {
                    "Value": 184,
                    "Unit": "69"
                }
            },
            {
                "Number": 3,
                "AD": "A",
                "Value": {
                    "Value": 745,
                    "Unit": "69"
                }
            },
            {
                "Number": 4,
                "AD": "A",
                "Value": {
                    "Value": 256,
                    "Unit": "69"
                }
            },
            {
                "Number": 5,
                "AD": "A",
                "Value": {
                    "Value": 706,
                    "Unit": "69"
                }
            },
            {
                "Number": 6,
                "AD": "A",
                "Value": {
                    "Value": 86,
                    "Unit": "69"
                }
            },
            {
                "Number": 7,
                "AD": "A",
                "Value": {
                    "Value": 606,
                    "Unit": "69"
                }
            },
            {
                "Number": 8,
                "AD": "A",
                "Value": {
                    "Value": 15,
                    "Unit": "69"
                }
            },
            {
                "Number": 9,
                "AD": "A",
                "Value": {
                    "Value": -851,
                    "Unit": "69"
                }
            },
            {
                "Number": 10,
                "AD": "A",
                "Value": {
                    "Value": -162,
                    "Unit": "69"
                }
            },
            {
                "Number": 11,
                "AD": "A",
                "Value": {
                    "Value": -433,
                    "Unit": "69"
                }
            },
            {
                "Number": 12,
                "AD": "A",
                "Value": {
                    "Value": -256,
                    "Unit": "69"
                }
            },
            {
                "Number": 13,
                "AD": "A",
                "Value": {
                    "Value": 237.5,
                    "Unit": "13"
                }
            },
            {
                "Number": 14,
                "AD": "A",
                "Value": {
                    "Value": 237.6,
                    "Unit": "13"
                }
            },
            {
                "Number": 15,
                "AD": "A",
                "Value": {
                    "Value": 238.4,
                    "Unit": "13"
                }
            },
            {
                "Number": 16,
                "AD": "A",
                "Value": {
                    "Value": 5.0,
                    "Unit": "63"
                }
            },
            {
                "Number": 17,
                "AD": "A",
                "Value": {
                    "Value": 0.8,
                    "Unit": "63"
                }
            },
            {
                "Number": 18,
                "AD": "A",
                "Value": {
                    "Value": 3.1,
                    "Unit": "63"
                }
            },
            {
                "Number": 19,
                "AD": "A",
                "Value": {
                    "Value": 1.1,
                    "Unit": "63"
                }
            },
            {
                "Number": 20,
                "AD": "A",
                "Value": {
                    "Value": 0.64,
                    "Unit": "24"
                }
            },
            {
                "Number": 21,
                "AD": "A",
                "Value": {
                    "Value": 0.47,
                    "Unit": "24"
                }
            },
            {
                "Number": 22,
                "AD": "A",
                "Value": {
                    "Value": 0.82,
                    "Unit": "24"
                }
            },
            {
                "Number": 23,
                "AD": "A",
                "Value": {
                    "Value": 0.07,
                    "Unit": "24"
                }
            },
            {
                "Number": 24,
                "AD": "A",
                "Value": {
                    "Value": -50.3,
                    "Unit": "54"
                }
            },
            {
                "Number": 25,
                "AD": "A",
                "Value": {
                    "Value": -62.1,
                    "Unit": "54"
                }
            },
            {
                "Number": 26,
                "AD": "A",
                "Value": {
                    "Value": -35.6,
                    "Unit": "54"
                }
            },
            {
                "Number": 27,
                "AD": "A",
                "Value": {
                    "Value": -86.7,
                    "Unit": "54"
                }
            },
            {
                "Number": 28,
                "AD": "D",
                "Value": {
                    "Value": 0,
                    "Unit": "44"
                }
            }
        ],
        "Modbus": []
    },
    "Status": "OK",
    "Status code": 0
}`

**Comment by Chris5020** [comment]
I updated to 1.3.0.1, but same log

```
2023-01-03 18:31:44.578 DEBUG (MainThread) [custom_components.ta_cmi] Try to fetch available device channels: 40
2023-01-03 18:31:44.602 WARNING (MainThread) [custom_components.ta_cmi] Error while communicating with a device (40): Failure during the CAN-request/parameter not available for this device

I tried to check changes in code, beta version has much less code than previous?
where could I verify this? in manifest it is still 1.2.0




```

**Comment by DeerMaximum** [comment]
Yes the version has less code because I reworked the python library to dynamically read the available channels and not read all channel types by hand. I haven't changed the version in the manifest file yet.
If you want to verify if you have the right version, you can look in the manifest file if ta-cmi version 1.0.0 is defined.
As for the error message, I'll get back to you in a few days.

**Comment by DeerMaximum** [comment]
I have extended the logging of the python library I use for the integration. If you install the latest beta and set the log level for the library to debug, we can better understand why the request to the C.M.I fails.

```yaml
logger:
  default: info
  logs:
    custom_components.ta_cmi: debug
    ta_cmi: debug
```

**Comment by DeerMaximum** [comment]
Can you try it again with the latest version, which should support devices without IO in config flow

**Comment by Chris5020** [comment]
sorry, nothing changed

2023-01-08 14:19:21.157 DEBUG (MainThread) [ta_cmi] Receive list of nodes from C.M.I
2023-01-08 14:19:21.178 DEBUG (MainThread) [ta_cmi] Received list of nodes from C.M.I: 40;
2023-01-08 14:19:21.178 DEBUG (MainThread) [custom_components.ta_cmi] Try to fetch device type: 40
2023-01-08 14:19:21.178 DEBUG (MainThread) [ta_cmi] Make request to device 40 from type 00 with parameters: I,O
2023-01-08 14:19:21.201 DEBUG (MainThread) [ta_cmi] Failed response received: {
"Header":{
"Version":6,
"Device":"8F",
"Timestamp":1673187561
},
"Data":{
},
"Status":"FAIL",
"Status code":2
}
2023-01-08 14:19:21.202 WARNING (MainThread) [custom_components.ta_cmi] Error while communicating with a device (40): Failure during the CAN-request/parameter not available for this device

**Comment by Chris5020** [comment]
OK, new version works, after a few minutes setups completes without any error!
THANK YOU!!

**Comment by DeerMaximum** [comment]
Nice that it works now
