### ISSUE TITLE
Adding data from DL-Bus

### ISSUE THREAD

**Issue by Twannyvb** [DeerMaximum/Technische-Alternative-CMI#18]
Hi, I really like this project!

I am using a RSM610 and can use the CAN data form it perfectly! But I have a question, there is a sensor connected to the DL-Bus of the RSM610 and this data is not available in Home Assistant? Did I configure something wrong or is this a feature what is not available (yet)?

Thanks in advance!
Twanny

**Comment by DeerMaximum** [comment]
Hi,

reading inputs via the DL-Bus is not supported for the RSM610 by the API. The DL-Bus is only supported for devices that end on x2 like the UVR16x2.

I hope the sensor is not too important for you.

**Comment by Twannyvb** [comment]
Oke, that is a bit crap. It is the room temperature sensor so kinda need it. The data is available in the TA app.

**Comment by DeerMaximum** [comment]
Since the RSM610 has the same functions as a UVR16x2 according to the manufacturer, it is worth trying to retrieve the data despite the incopatibility.

Go to this page and send me the answer: http://CMI_IP/INCLUDE/api.cgi?jsonnode=NOTE_ID&jsonparam=D
Replace CMI_IP with the IP address of your CMI and NOTE_ID with the NODE ID of the RSM610.

With a little luck you can read the data.

**Comment by Twannyvb** [comment]
Looks like it works:

{ "Header":{ "Version":5, "Device":"88", "Timestamp":1670526003 }, "Data":{ "DL-Bus":[ { "Number":1, "AD":"A", "Value":{ "Value":18.8, "Unit":"46", "RAS":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":0.0, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":58.9, "Unit":"8" } }, { "Number":4, "AD":"A", "Value":{ "Value":10.6, "Unit":"1" } }]}, "Status":"OK", "Status code":0 }

The value 18.8 is the current room temperature.

**Comment by DeerMaximum** [comment]
Can you install the dev-1.1.2.1 version and see if you can read the data from the sensor?

**Comment by Twannyvb** [comment]
Hi, that is a quick Dev version. It works perfectly!!
Also de unit of the channels is correct, do you want me to check something extra? Is the CAN node ID detected because I did not need to set it? I was thinking of expanding my set with a CAN-I/O45 and a sensor connected to de DL-bus, will do that probably.
Big thanks for the effort!

**Comment by DeerMaximum** [comment]
Nice that it works. The CMI provides the integration with a list of all devices connected to the CAN-Bus, these are checked for compatibility and displayed accordingly.

**Comment by DeerMaximum** [comment]
Support for the DL-Bus of CAN-I/O45 is added in version 1.8.9
