### ISSUE TITLE
No dl bus support for UVR610 in beta 1.3.0.1?

### ISSUE THREAD

**Issue by martinusgithubius** [DeerMaximum/Technische-Alternative-CMI#24]
Hi,

Great integration, thanks a lot - but I cannot make it to work w/i my HA. I just installed the latest beta-1.3.0.1 to log a newly installed CMI with UVR610 connected. (CAN Node 1). (Only) one DL client is connected to the UVR with three dl-inputs defined .The data can be accessed via an http request (.../INCLUDE/api.cgi?jsonnode="+can_node+"&jsonparam=D).
W/i the HA integration the CAN node shows up as 1 device:
Node 1: Type: UVR610, Inputs: 0, Outputs: 0, MBus: 0
I cannot access or see any sensors from the DL bus. Remember: other sensors are not connected.
log file (info level) gives 'setting up sensor.ta_cmi and binary_sensor.ta_cmi, not more. 

When setting up the integration I played around with auto-detecting devices and with setting-up specific devices, which ended up in the attached core.config_entries.

BTW, it neither worked with the previous official release.

Maybe I am missing something fundamental?

Thanks for your help.

Mart

    {
        "entry_id": "5429515fdde15blabla",
        "version": 1,
        "domain": "ta_cmi",
        "title": "C.M.I",
        "data": {
          "host": "http://cmi.internal",
          "username": "admin",
          "password": "xxx",
          "devices": [
            {
              "id": "1",
              "fetchmode": "defined",
              "type": "UVR610",
              "channels": []
            }
          ]
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": "user"
      },
      {
        "entry_id": "932026874100b2238blabla",
        "version": 1,
        "domain": "ta_cmi",
        "title": "C.M.I",
        "data": {
          "host": "http://cmi.internal",
          "username": "admin",
          "password": "xxx",
          "devices": [
            {
              "id": "1",
              "fetchmode": "all",
              "type": "UVR610",
              "channels": [
                {
                  "type": "dl-bus",
                  "id": 1,
                  "name": "cmitest1",
                  "device_class": ""
                },
                {
                  "type": "dl-bus",
                  "id": 2,
                  "name": "cmitest2",
                  "device_class": ""
                },
                {
                  "type": "dl-bus",
                  "id": 3,
                  "name": "cmitest3",
                  "device_class": ""
                },
                {
                  "type": "dl-bus",
                  "id": 4,
                  "name": "cmitest4",
                  "device_class": ""
                },
                {
                  "type": "analog logging",
                  "id": 1,
                  "name": "cmilog1",
                  "device_class": ""
                }
              ]
            }
          ]
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      }
    ]

**Comment by DeerMaximum** [comment]
No, you did not forget anything during setup. According to the API documentation, the DL bus is only supported by devices that end on x2. But since it is the case with many devices that they support more than stated in the documentation, I will add support for the DL bus for the UVR610 in the final version 1.3.0.

**Comment by DeerMaximum** [comment]
In the latest beta version, the DL bus should be available. Set up the integration again via the GUI.
If not, you can put the integration and the underlying library into debug modes and send me the associated logs.

```yaml
logger:
  default: info
  logs:
    custom_components.ta_cmi: debug
    ta_cmi: debug
```

**Comment by martinusgithubius** [comment]
dl-bus support still does not show up. Is this the output you asked for? This is what was dumped when I enabled/disabled debug logging in the context menu of the CMI integration. (btw, I noted that dl-bus support is listed for RSM610, but not for UVR610 in your table)

23-01-08 18:24:13.240 INFO (MainThread) [homeassistant.setup] Setting up ta_cmi
2023-01-08 18:24:13.240 INFO (MainThread) [homeassistant.setup] Setup of domain ta_cmi took 0.0 seconds
2023-01-08 18:24:13.256 DEBUG (MainThread) [custom_components.ta_cmi] Try to update device: 1
2023-01-08 18:24:13.256 DEBUG (MainThread) [ta_cmi] Update device: 1
2023-01-08 18:24:13.256 DEBUG (MainThread) [ta_cmi] Make request to device 1 from type 91 with parameters: I,O,M
2023-01-08 18:24:21.944 DEBUG (MainThread) [custom_components.ta_cmi] Finished fetching ta_cmi data in 8.688 seconds (success: True)
2023-01-08 18:24:22.011 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.ta_cmi
2023-01-08 18:24:22.014 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.ta_cmi

**Comment by DeerMaximum** [comment]
Yes, that is the output I asked for. 

I have now added DL-Bus support for the UVR610 and adjusted the table.

**Comment by martinusgithubius** [comment]
great work, thanks a lot.
