### ISSUE TITLE
Support for Modbus Input Output in CAN-BC2

### ISSUE THREAD

**Issue by dreitakter** [DeerMaximum/Technische-Alternative-CMI#30]
The query Option for the Json-Api is "AM".

Here is a Sample json Output.

`{ "Header":{ "Version":6, "Device":"8D", "Timestamp":1672830232 }, "Data":{ "Modbus":[ { "Number":1, "AD":"A", "Value":{ "Value":6.7, "Unit":"58" } }, { "Number":2, "AD":"A", "Value":{ "Value":18.1, "Unit":"58" } }, { "Number":3, "AD":"A", "Value":{ "Value":56.5, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":8.3, "Unit":"58" } }, { "Number":5, "AD":"A", "Value":{ "Value":7.4, "Unit":"58" } }, { "Number":6, "AD":"A", "Value":{ "Value":5.0, "Unit":"58" } }, { "Number":7, "AD":"A", "Value":{ "Value":30.6, "Unit":"1" } }, { "Number":8, "AD":"A", "Value":{ "Value":-1.2, "Unit":"1" } }, { "Number":9, "AD":"A", "Value":{ "Value":19, "Unit":"0" } }, { "Number":10, "AD":"A", "Value":{ "Value":31, "Unit":"0" } }, { "Number":11, "AD":"A", "Value":{ "Value":201, "Unit":"0" } }, { "Number":12, "AD":"A", "Value":{ "Value":9.5, "Unit":"58" } }, { "Number":13, "AD":"A", "Value":{ "Value":56.4, "Unit":"1" } }, { "Number":14, "AD":"A", "Value":{ "Value":50, "Unit":"0" } }, { "Number":15, "AD":"A", "Value":{ "Value":42.6, "Unit":"1" } }, { "Number":16, "AD":"A", "Value":{ "Value":42.6, "Unit":"1" } }, { "Number":17, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":18, "AD":"A", "Value":{ "Value":40.6, "Unit":"1" } }, { "Number":19, "AD":"A", "Value":{ "Value":0.0, "Unit":"8" } }, { "Number":20, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":21, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":22, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":23, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":24, "AD":"A", "Value":{ "Value":93.5, "Unit":"8" } }, { "Number":25, "AD":"A", "Value":{ "Value":28.2, "Unit":"1" } }, { "Number":26, "AD":"A", "Value":{ "Value":25.9, "Unit":"1" } }, { "Number":27, "AD":"A", "Value":{ "Value":28.4, "Unit":"1" } }, { "Number":28, "AD":"A", "Value":{ "Value":3.7, "Unit":"1" } }, { "Number":29, "AD":"A", "Value":{ "Value":2, "Unit":"0" } }, { "Number":30, "AD":"A", "Value":{ "Value":2, "Unit":"0" } }, { "Number":31, "AD":"A", "Value":{ "Value":43.0, "Unit":"1" } }, { "Number":32, "AD":"A", "Value":{ "Value":-3276.7, "Unit":"1" } }, { "Number":33, "AD":"A", "Value":{ "Value":-3276.7, "Unit":"1" } }, { "Number":34, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":35, "AD":"A", "Value":{ "Value":0.45, "Unit":"10" } }, { "Number":36, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":37, "AD":"A", "Value":{ "Value":46.0, "Unit":"58" } }, { "Number":38, "AD":"A", "Value":{ "Value":43.0, "Unit":"58" } }, { "Number":39, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":40, "AD":"A", "Value":{ "Value":120, "Unit":"0" } }, { "Number":41, "AD":"A", "Value":{ "Value":240, "Unit":"0" } }, { "Number":42, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":43, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":44, "AD":"A", "Value":{ "Value":0.0, "Unit":"8" } }, { "Number":45, "AD":"A", "Value":{ "Value":6.6, "Unit":"58" } }, { "Number":46, "AD":"A", "Value":{ "Value":3, "Unit":"0" } }, { "Number":47, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":48, "AD":"A", "Value":{ "Value":-1, "Unit":"0" } }, { "Number":49, "AD":"A", "Value":{ "Value":2, "Unit":"0" } }, { "Number":50, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":51, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":52, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":53, "AD":"A", "Value":{ "Value":3, "Unit":"0" } }, { "Number":54, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":55, "AD":"A", "Value":{ "Value":10100000, "Unit":"0" } }, { "Number":56, "AD":"A", "Value":{ "Value":3115, "Unit":"0" } }, { "Number":57, "AD":"A", "Value":{ "Value":5.1, "Unit":"58" } }, { "Number":58, "AD":"A", "Value":{ "Value":20.0, "Unit":"1" } }, { "Number":59, "AD":"A", "Value":{ "Value":7536, "Unit":"0" } }, { "Number":60, "AD":"A", "Value":{ "Value":867, "Unit":"0" } }, { "Number":61, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":62, "AD":"A", "Value":{ "Value":202, "Unit":"0" } }, { "Number":63, "AD":"A", "Value":{ "Value":0.86, "Unit":"10" } }, { "Number":64, "AD":"A", "Value":{ "Value":12604, "Unit":"0" } }]}, "Status":"OK", "Status code":0 }`

Thanks for your great Work :)

**Comment by DeerMaximum** [comment]
Modbus is already supported for CAN-BC2 and should also be displayed in the integration. Is this not the case for you?

**Comment by dreitakter** [comment]
No, it is not working for me.
Can I provide some kind of logfile to Help finding the Error?

**Comment by DeerMaximum** [comment]
Yes, if you put the integration and the underlying library in debug mode and send me the logs, that will help a lot.

```yaml
logger:
  default: info
  logs:
    custom_components.ta_cmi: debug
    ta_cmi: debug
```

**Comment by dreitakter** [comment]
[home-assistant_2023-01-10T19-57-22.950Z.log.txt](https://github.com/DeerMaximum/Technische-Alternative-CMI/files/10386379/home-assistant_2023-01-10T19-57-22.950Z.log.txt)
Hier das log

**Comment by DeerMaximum** [comment]
Thanks for the log, but you need to enable logging for `ta_cmi` library as described above in the configuration file, only then I can track what requests are made to the CMI.

The log should then contain something like this:
```
2023-01-05 19:05:47.764 DEBUG (MainThread) [ta_cmi] Receive list of nodes from C.M.I
2023-01-05 19:05:47.782 DEBUG (MainThread) [ta_cmi] Received list of nodes from C.M.I: 40;
2023-01-05 19:05:47.782 DEBUG (MainThread) [custom_components.ta_cmi] Try to fetch device type: 40
2023-01-05 19:05:47.782 DEBUG (MainThread) [ta_cmi] Make request to device 40 from type 00 with parameters: I,O
```

**Comment by dreitakter** [comment]
```
logger:
  default: info
  logs:
    custom_components.ta_cmi: debug
    ta_cmi: debug
```

that is what I have in configuration.yaml

I have restartet HA and set up the integration again.
here is the new log:
[home-assistant_ta_cmi_2023-01-11T09-50-46.701Z.log](https://github.com/DeerMaximum/Technische-Alternative-CMI/files/10390966/home-assistant_ta_cmi_2023-01-11T09-50-46.701Z.log)

**Comment by DeerMaximum** [comment]
It looks like the CMI returns an invalid JSON response. Can you tell what the response is for the following request?

`http://CMI_IP/INCLUDE/api.cgi?jsonnode=NODE_ID&jsonparam=I,O,M,AM,Ak`

**Comment by dreitakter** [comment]
Here is the Output

`{ "Header":{ "Version":6, "Device":"8D", "Timestamp":1673471470 }, "Data":{ , "MBus":[ ], "Modbus":[ { "Number":1, "AD":"A", "Value":{ "Value":9.8, "Unit":"58" } }, { "Number":2, "AD":"A", "Value":{ "Value":16.0, "Unit":"58" } }, { "Number":3, "AD":"A", "Value":{ "Value":26.3, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":21.0, "Unit":"58" } }, { "Number":5, "AD":"A", "Value":{ "Value":14.8, "Unit":"58" } }, { "Number":6, "AD":"A", "Value":{ "Value":13.8, "Unit":"58" } }, { "Number":7, "AD":"A", "Value":{ "Value":25.9, "Unit":"1" } }, { "Number":8, "AD":"A", "Value":{ "Value":9.6, "Unit":"1" } }, { "Number":9, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":10, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":11, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":12, "AD":"A", "Value":{ "Value":11.4, "Unit":"58" } }, { "Number":13, "AD":"A", "Value":{ "Value":51.4, "Unit":"1" } }, { "Number":14, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":15, "AD":"A", "Value":{ "Value":31.2, "Unit":"1" } }, { "Number":16, "AD":"A", "Value":{ "Value":30.2, "Unit":"1" } }, { "Number":17, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":18, "AD":"A", "Value":{ "Value":41.6, "Unit":"1" } }, { "Number":19, "AD":"A", "Value":{ "Value":0.0, "Unit":"8" } }, { "Number":20, "AD":"A", "Value":{ "Value":25, "Unit":"0" } }, { "Number":21, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":22, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":23, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":24, "AD":"A", "Value":{ "Value":100.0, "Unit":"8" } }, { "Number":25, "AD":"A", "Value":{ "Value":26.2, "Unit":"1" } }, { "Number":26, "AD":"A", "Value":{ "Value":25.1, "Unit":"1" } }, { "Number":27, "AD":"A", "Value":{ "Value":26.1, "Unit":"1" } }, { "Number":28, "AD":"A", "Value":{ "Value":4.0, "Unit":"1" } }, { "Number":29, "AD":"A", "Value":{ "Value":2, "Unit":"0" } }, { "Number":30, "AD":"A", "Value":{ "Value":2, "Unit":"0" } }, { "Number":31, "AD":"A", "Value":{ "Value":34.0, "Unit":"1" } }, { "Number":32, "AD":"A", "Value":{ "Value":-3276.7, "Unit":"1" } }, { "Number":33, "AD":"A", "Value":{ "Value":-3276.7, "Unit":"1" } }, { "Number":34, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":35, "AD":"A", "Value":{ "Value":0.00, "Unit":"10" } }, { "Number":36, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":37, "AD":"A", "Value":{ "Value":46.0, "Unit":"58" } }, { "Number":38, "AD":"A", "Value":{ "Value":43.0, "Unit":"58" } }, { "Number":39, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":40, "AD":"A", "Value":{ "Value":120, "Unit":"0" } }, { "Number":41, "AD":"A", "Value":{ "Value":240, "Unit":"0" } }, { "Number":42, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":43, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":44, "AD":"A", "Value":{ "Value":0.0, "Unit":"8" } }, { "Number":45, "AD":"A", "Value":{ "Value":6.6, "Unit":"58" } }, { "Number":46, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":47, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":48, "AD":"A", "Value":{ "Value":-1, "Unit":"0" } }, { "Number":49, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":50, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":51, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":52, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":53, "AD":"A", "Value":{ "Value":3, "Unit":"0" } }, { "Number":54, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":55, "AD":"A", "Value":{ "Value":10100000, "Unit":"0" } }, { "Number":56, "AD":"A", "Value":{ "Value":0, "Unit":"0" } }, { "Number":57, "AD":"A", "Value":{ "Value":0.0, "Unit":"58" } }, { "Number":58, "AD":"A", "Value":{ "Value":20.0, "Unit":"1" } }, { "Number":59, "AD":"A", "Value":{ "Value":7633, "Unit":"0" } }, { "Number":60, "AD":"A", "Value":{ "Value":867, "Unit":"0" } }, { "Number":61, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":62, "AD":"A", "Value":{ "Value":202, "Unit":"0" } }, { "Number":63, "AD":"A", "Value":{ "Value":0.52, "Unit":"10" } }, { "Number":64, "AD":"A", "Value":{ "Value":12556, "Unit":"0" } }], "KNX":[ ]}, "Status":"OK", "Status code":0 }`

**Comment by dreitakter** [comment]
Its the Combination of "I" and/or "O" and the Other Parameters. 
I have tried multiple Combinations. Everytime "I" or "O" is involved the wrong formed json is produced.
Example "I,M"
`{ "Header":{ "Version":6, "Device":"8D", "Timestamp":1673472371 }, "Data":{ , "MBus":[ ]}, "Status":"OK", "Status code":0 }`

**Comment by dreitakter** [comment]
If I combine I,O the Output is ok. 

"I,O"
`{ "Header":{ "Version":6, "Device":"8D", "Timestamp":1673523415 }, "Data":{ }, "Status":"OK", "Status code":0 }`

But any additional Parameter leads to the wrong json.

"I,O,M"
`{ "Header":{ "Version":6, "Device":"8D", "Timestamp":1673523458 }, "Data":{ , "MBus":[ ]}, "Status":"OK", "Status code":0 }`

**Comment by dreitakter** [comment]
I have updated to 1.4.0 but the Error is Not gone.
In Setup process there is an Error.
Here is the Log:
[home-assistant_2023-01-15T19-04-37.119Z.log.txt](https://github.com/DeerMaximum/Technische-Alternative-CMI/files/10420976/home-assistant_2023-01-15T19-04-37.119Z.log.txt)

**Comment by dreitakter** [comment]
That Sounds good :)
Let me know when I can Test this.
Would Love to use this addon

**Comment by DeerMaximum** [comment]
Can you install the latest beta version (beta-1.4.1) and see if the error still occurs?

**Comment by dreitakter** [comment]
![image](https://user-images.githubusercontent.com/7339920/213256323-02e2649e-e20a-4313-80f7-affbeb499941.png)

Looks good :)

Here are my Sensors:
![image](https://user-images.githubusercontent.com/7339920/213256711-91253fbc-bdd5-4004-ace3-5e6a832a812c.png)

Thanks for your work
