### ISSUE TITLE
Change Fixvalues

### ISSUE THREAD

**Issue by dreitakter** [DeerMaximum/Technische-Alternative-CMI#31]
At the moment I Change the Fixvalues with a REST command directly send from Home assistant. I only Change "WW Sollwert".

Would be nice to do this with your custom component.

Read all changeable values and generate a Switch for ON/OFF entitys, Input_Select for multiple Status Like ON/OFF/Auto and a Climate entity for Tempratures and so on...

Do you think this is possible?

**Comment by DeerMaximum** [comment]
The CMI API I use for the queries is read only. Which rest command do you use to change the values?

**Comment by dreitakter** [comment]
Its not the official API but it works ;)

rest_command:
  heizung_warmwasser_34_grad:
    url: http://USERNAME:PASSWORD@cmi.fritz.box/INCLUDE/change.cgi?changeadrx2=0400144414D101&changetox2=34.0
    headers:
      Referer: http://cmi.fritz.box/schema.html
  heizung_warmwasser_43_grad:
    url: http://USERNAME:PASSWORD@cmi.fritz.box/INCLUDE/change.cgi?changeadrx2=0400144414D101&changetox2=43.0
    headers:
      Referer: http://cmi.fritz.box/schema.html

I have debugged the web-request and try and error. The Header Referer is not optional! It will not work without this header...

I dont know if a generic solution is possible.
I want to achive the following:
-> like a thermostat in HA:
  -> current_temprature = WW_ISTWERT
  -> set_temprature = WW_SOLLWERT

this should be a real climate-entity in HA -> nice and usable UI

**Comment by ptar** [comment]
In the CMI, one can define MODBUS sources as inputs. see https://help.ta.co.at/EN/CMIHELP/modbus_1.htm?ms=CQAQCA%3D%3D&st=MA%3D%3D&sct=MA%3D%3D&mw=MjQw#
The inputs are read in a defined interval.

Would it be possible to provide MODBUS outputs which could be used as inputs as described above?
That is, you don't have to set the value from HA, but the CMI requests it. Therefore, no API to write to the CMI is needed.

I would like to use an information available in HA as an input to control heater circuit 2.

**Comment by mannebk79** [comment]
How about this:

use Deers TA-CMI integration for reading values from CMI and acting on these data in HA for comfort only.

then use the HA modbus component (see here: https://www.home-assistant.io/integrations/modbus/) for writing data to the UVR?

at least thats what I will try to setup, as i want a pwm pump and a pmw controlled relay to act on settings collected by HA and then provided by modbus to CMI. and just in case if HA goes down, the uvr will have a backup plan for emergency operations with no comfy, but still hot water and heating available...

**Comment by DeerMaximum** [comment]
I think that the suggested way of mannebk79 is the best solution to change values. So I will close the issue.
