### ISSUE TITLE
no more log_entities (analog/digital) after todays update 1.3.0

### ISSUE THREAD

**Issue by meichhorn** [DeerMaximum/Technische-Alternative-CMI#34]
Input/Output Entities still fine
all entities (for example Mischer % - Value) from a function logged to Analog_Out_XY is gone from the HA-Entities.

## Debug log
no log entry for anything from hacs-ta

maybe there is a chance to switch back to the version before?
hope i have provided enough Info?
Thanks for any suggestion!

**Comment by meichhorn** [comment]
I use a UVR16X2.
I found out how to downgrade to 1.2 - now everything working fine again.

**Comment by DeerMaximum** [comment]
Can you install the latest beta version (beta-1.4.1) and see if the error still occurs?

**Comment by meichhorn** [comment]
additional Info on 1.41 beta with uvr16x2:
see this error in the integrations-site:

--> Retrying setup: Failure during the CAN-request/parameter not available for this device

now giving up and go back to 1.2 for this time

**Comment by DeerMaximum** [comment]
I have now published another beta version. With this one it should work.

**Comment by meichhorn** [comment]
i tried, but it did not work out - all the same as before  - see screenshot
![Screenshot 2023-01-19 190320](https://user-images.githubusercontent.com/49484744/213524554-df7bf9da-f52f-422d-9878-02bd968fa802.jpg)

**Comment by DeerMaximum** [comment]
That's strange, because I have a UVR16x2 in use myself and the error does not occur for me. 
Could you set the integration to the debug log level and send me the logs?

```yaml
logger:
  default: info
  logs:
    custom_components.ta_cmi: debug
    ta_cmi: debug
```

**Comment by meichhorn** [comment]
error is now located ;-) 
my can bus speed is at 500kbit/s because i have short cables and everything is much more responsive...
tried and your integration beta1.4.1 again and it works fine at 50 kbit/s
the regular Version 1.2 had no problems with my 500 kbit/s...
maybe you could check the timing so it is possible to spedd up a bit again ;-) 
thank you

**Comment by DeerMaximum** [comment]
OK, glad to hear it's working now.
