### ISSUE TITLE
Unit for update interval / numeric input field

### ISSUE THREAD

**Issue by mscfw2021** [DeerMaximum/Technische-Alternative-CMI#36]
Because CMI is a bit "sensitive" in regards of the update interval, the new configuration parameter is very useful. Is it possible to add a unit (minutes / seconds / ...) to the UI? I have no idea what value is actually used (10?) - seem to be longer than a minute, but less than 10 minutes - but only guessing.
thanks for your great work

**Comment by DeerMaximum** [comment]
Thanks for the hint, I have overlooked the unit. 

The standard query interval is 10 minutes.
