### ISSUE TITLE
I have updated to 1.4.0 but the Error is Not gone.

### ISSUE THREAD

**Issue by dreitakter** [DeerMaximum/Technische-Alternative-CMI#38]
I have updated to 1.4.0 but the Error is Not gone.
In Setup process there is an Error.
Here is the Log:
[home-assistant_2023-01-15T19-04-37.119Z.log.txt](https://github.com/DeerMaximum/Technische-Alternative-CMI/files/10420976/home-assistant_2023-01-15T19-04-37.119Z.log.txt)

_Originally posted by @dreitakter in https://github.com/DeerMaximum/Technische-Alternative-CMI/issues/30#issuecomment-1383227077_

**Comment by DeerMaximum** [comment]
I have reopened #30
