### ISSUE TITLE
change start of integration

### ISSUE THREAD

**Issue by molelightn** [DeerMaximum/Technische-Alternative-CMI#48]
**Is your feature request related to a problem? Please describe.**

Due to long cycle times from CMI requests the startup of this integration surpress a sucessfull start of HA.
This causes my automations to not work until TA integration is fully started.
A full start takes about 10-15min actually.

**Describe the solution you'd like**

do not delay a full start of HA, may the first poll of sensors from CMI can be in "background"?

**Describe alternatives you've considered**

not sure how alternatives can look like

**Additional context**

HA also reports:

Setup timed out for stage 2 - moving forward
4. April 2023 um 21:23:56 – (WARNUNG) bootstrap.py

i guess the start of HA is meant with this Warning?

PS: i would like to donate you for your work, let me know how to.

**Comment by DeerMaximum** [comment]
I can't delay the start of integration without also delaying the start of HA. 


The problem that the start of the integration can take quite a long time with many devices is known to me and is a limitation of C.M.I.. Therefore I am currently also testing the possibility to retrieve the data via CanOverEthernet into the integration. This way the values will be transmitted directly from the C.M.I. to HA and the long waiting time at startup will be solved.

**Comment by DeerMaximum** [comment]
If you want to try reading the data via CoE, then use [Technical-Alternative-CoE](https://github.com/DeerMaximum/Technische-Alternative-CoE).
