### ISSUE TITLE
Support values from CAN/MT connected to UVR1611

### ISSUE THREAD

**Issue by seveny42** [DeerMaximum/Technische-Alternative-CMI#53]
**Is your feature request related to a problem? Please describe.**
I can see my CAN/MT including the values in the CMI frontend as node 50. But I do net get info in HA of node50. Only node1.

**Describe the solution you'd like**
Also offer the values for can node 50 in HA

**Describe alternatives you've considered**
I was able to get the values thru a http-request with my older bl-net. Can these values thru CMI also be http-pulled instead of using json maybe? 

**Additional context**
Screenshots about the feature request:
<img width="408" alt="Bildschirmfoto 2023-04-25 um 19 41 57" src="https://user-images.githubusercontent.com/14195204/234358625-166529f7-0e4d-46f1-a751-4272d84649a3.png">
<img width="425" alt="Bildschirmfoto 2023-04-25 um 19 41 52" src="https://user-images.githubusercontent.com/14195204/234358635-332f0b32-5542-49af-aaaf-cdc56983de8c.png">

**Comment by DeerMaximum** [comment]
Can you call this URL and send me the answer? Depending on whether the CAN/MT can be read with this URL I can add it, since it is not officially supported by the API. 

But for other devices often unsupported data can be read out.

`http://CMI-IP/INCLUDE/api.cgi?jsonnode=50&jsonparam=I,O`

**Comment by seveny42** [comment]
{ "Header":{ "Version":6, "Device":"81", "Timestamp":1682535922 }, "Data":{ }, "Status":"DEVICE NOT SUPPORTED", "Status code":5 }

**Comment by DeerMaximum** [comment]
As it looks the device is not supported by the Json Api. 
Maybe you can retrieve the data via the CoE interface. Please use [this](https://github.com/DeerMaximum/Technische-Alternative-CoE) integration for that.

**Comment by seveny42** [comment]
Thanks, but on my Syn NAS with docker the CoE Interface won't install:

Diese Weiterleitung wird von deiner Home Assistant-Installation nicht unterstützt. Benötigt entweder das Home Assistant-Betriebssystem oder die Home Assistant Supervised-Installationsmethode. Weitere Informationen findest du unter [Dokumentation](https://www.home-assistant.io/installation).
