### ISSUE TITLE
UVR16x2 - added DL devices - Sensordata of DL not in HA

### ISSUE THREAD

**Issue by peter-mul** [DeerMaximum/Technische-Alternative-CMI#56]
The UVR16x2 was added and all of its sensordata was available in HA.

Weeks later I added 2 DL devices.
Reloading the integration or deactivating and activating the uvr16x2 did not help. No data from the DL devices was available.

The expectation is that the sensordata from the DL devices is retrieved and visible in HA too.

testet with 1.7.0

The DL Sensordata can be retrieved using the url

http://10.1.0.46/INCLUDE/api.cgi?jsonnode=1&jsonparam=D

{ "Header":{ "Version":6, "Device":"87", "Timestamp":[1684786742](tel:1684786742) }, "Data":{ "DL-Bus":[ { "Number":1, "AD":"A", "Value":{ "Value":21.5, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":21.9, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":21.9, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":21.9, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":22.2, "Unit":"1" } }, { "Number":6, "AD":"A", "Value":{ "Value":22.3, "Unit":"1" } }, { "Number":7, "AD":"A", "Value":{ "Value":22.3, "Unit":"1" } }, { "Number":8, "AD":"A", "Value":{ "Value":21.3, "Unit":"1" } }, { "Number":9, "AD":"A", "Value":{ "Value":30.9, "Unit":"1" } }, { "Number":10, "AD":"A", "Value":{ "Value":22.2, "Unit":"1" } }]}, "Status":"OK", "Status code":0 }

The log tells…

2023-05-22 20:39:15.363 DEBUG (MainThread) [ta_cmi] Update device: 1
2023-05-22 20:39:15.364 DEBUG (MainThread) [ta_cmi] Make request to device 1 with parameters: I,O,D,Sg,Sd,St,Ss
2023-05-22 20:40:18.687 DEBUG (MainThread) [ta_cmi] Make request to device 1 with parameters: La,Ld
2023-05-22 20:40:40.448 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140593536172096] Connection closed by client
2023-05-22 20:40:40.455 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140593536009504] Connection closed by client
2023-05-22 20:41:21.391 DEBUG (MainThread) [ta_cmi] Update device: 50
2023-05-22 20:41:21.391 DEBUG (MainThread) [ta_cmi] Make request to device 50 with parameters: I,O

The uvr16x2 is device 1
device 50 is a CAN-MTx2

Thanks for your work!

**Comment by DeerMaximum** [comment]
Can you send me the data you get from the device with the I,O,D,Sg,Sd,St,Ss parameters.
http://10.1.0.46/INCLUDE/api.cgi?jsonnode=1&jsonparam=I,O,D,Sg,Sd,St,Ss

**Comment by peter-mul** [comment]
http://10.1.0.46/INCLUDE/api.cgi?jsonnode=1&jsonparam=I,O,D,Sg,Sd,St,Ss

{ "Header":{ "Version":6, "Device":"87", "Timestamp":[1684861783](tel:1684861783) }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":18.2, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":18.1, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":18.1, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":18.2, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":18.0, "Unit":"1" } }, { "Number":6, "AD":"A", "Value":{ "Value":18.1, "Unit":"1" } }, { "Number":7, "AD":"A", "Value":{ "Value":4.95, "Unit":"23" } }, { "Number":8, "AD":"A", "Value":{ "Value":-0.01, "Unit":"23" } }, { "Number":9, "AD":"A", "Value":{ "Value":19.1, "Unit":"1" } }, { "Number":10, "AD":"A", "Value":{ "Value":22.1, "Unit":"1" } }, { "Number":11, "AD":"A", "Value":{ "Value":21.8, "Unit":"1" } }, { "Number":12, "AD":"A", "Value":{ "Value":20.7, "Unit":"1" } }, { "Number":13, "AD":"A", "Value":{ "Value":0, "Unit":"3" } }, { "Number":14, "AD":"A", "Value":{ "Value":18.3, "Unit":"1" } }, { "Number":15, "AD":"A", "Value":{ "Value":0, "Unit":"3" } }, { "Number":16, "AD":"A", "Value":{ "Value":0, "Unit":"3" } }], "Outputs":[ { "Number":1, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":3, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":7, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":12, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }, { "Number":13, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }, { "Number":14, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":15, "AD":"A", "Value":{ "State":0, "Value":0.0, "Unit":"8" } }, { "Number":16, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }], "DL-Bus":[ { "Number":1, "AD":"A", "Value":{ "Value":20.6, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":20.6, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":20.7, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":20.7, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":20.6, "Unit":"1" } }, { "Number":6, "AD":"A", "Value":{ "Value":20.6, "Unit":"1" } }, { "Number":7, "AD":"A", "Value":{ "Value":20.9, "Unit":"1" } }, { "Number":8, "AD":"A", "Value":{ "Value":21.9, "Unit":"1" } }, { "Number":9, "AD":"A", "Value":{ "Value":21.9, "Unit":"1" } }, { "Number":10, "AD":"A", "Value":{ "Value":20.6, "Unit":"1" } }], "General":[ { "Number":1, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":3, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":5, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":7, "AD":"A", "Value":{ "Value":0.00, "Unit":"21" } }, { "Number":8, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":9, "AD":"D", "Value":{ "Value":1, "Unit":"44" } }, { "Number":10, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":11, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":12, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":13, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":14, "AD":"A", "Value":{ "Value":51020, "Unit":"0" } }], "Date":[ { "Number":1, "AD":"A", "Value":{ "Value":23, "Unit":"0" } }, { "Number":2, "AD":"A", "Value":{ "Value":5, "Unit":"0" } }, { "Number":3, "AD":"A", "Value":{ "Value":23, "Unit":"0" } }, { "Number":4, "AD":"A", "Value":{ "Value":2, "Unit":"0" } }, { "Number":5, "AD":"A", "Value":{ "Value":21, "Unit":"0" } }, { "Number":6, "AD":"A", "Value":{ "Value":143, "Unit":"0" } }, { "Number":7, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":8, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":9, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":10, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }], "Time":[ { "Number":1, "AD":"A", "Value":{ "Value":28, "Unit":"4" } }, { "Number":2, "AD":"A", "Value":{ "Value":18, "Unit":"5" } }, { "Number":3, "AD":"A", "Value":{ "Value":17, "Unit":"15" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":7, "AD":"D", "Value":{ "Value":1, "Unit":"44" } }, { "Number":8, "AD":"A", "Value":{ "Value":1038, "Unit":"60" } }], "Sun":[ { "Number":1, "AD":"A", "Value":{ "Value":309, "Unit":"60" } }, { "Number":2, "AD":"A", "Value":{ "Value":1243, "Unit":"60" } }, { "Number":3, "AD":"A", "Value":{ "Value":0, "Unit":"5" } }, { "Number":4, "AD":"A", "Value":{ "Value":729, "Unit":"5" } }, { "Number":5, "AD":"A", "Value":{ "Value":205, "Unit":"5" } }, { "Number":6, "AD":"A", "Value":{ "Value":0, "Unit":"5" } }, { "Number":7, "AD":"A", "Value":{ "Value":31.3, "Unit":"54" } }, { "Number":8, "AD":"A", "Value":{ "Value":265.7, "Unit":"54" } }, { "Number":9, "AD":"D", "Value":{ "Value":1, "Unit":"44" } }, { "Number":10, "AD":"A", "Value":{ "Value":776, "Unit":"60" } }]}, "Status":"OK", "Status code":0 }

**Comment by peter-mul** [comment]
maybe you also need the output of
http://10.1.0.46/INCLUDE/api.cgi?jsonnode=1&jsonparam=La,Ld

{ "Header":{ "Version":6, "Device":"87", "Timestamp":[1684862220](tel:1684862220) }, "Data":{ "Logging Analog":[ { "Number":1, "AD":"A", "Value":{ "Value":18.2, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":18.1, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":18.1, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":18.2, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":18.0, "Unit":"1" } }, { "Number":6, "AD":"A", "Value":{ "Value":18.1, "Unit":"1" } }, { "Number":7, "AD":"A", "Value":{ "Value":5.08, "Unit":"23" } }, { "Number":8, "AD":"A", "Value":{ "Value":-0.01, "Unit":"23" } }, { "Number":9, "AD":"A", "Value":{ "Value":19.1, "Unit":"1" } }, { "Number":10, "AD":"A", "Value":{ "Value":22.1, "Unit":"1" } }, { "Number":11, "AD":"A", "Value":{ "Value":21.8, "Unit":"1" } }, { "Number":12, "AD":"A", "Value":{ "Value":20.7, "Unit":"1" } }, { "Number":13, "AD":"A", "Value":{ "Value":0, "Unit":"3" } }, { "Number":14, "AD":"A", "Value":{ "Value":18.3, "Unit":"1" } }, { "Number":15, "AD":"A", "Value":{ "Value":0, "Unit":"3" } }, { "Number":16, "AD":"A", "Value":{ "Value":0, "Unit":"3" } }, { "Number":17, "AD":"A", "Value":{ "Value":20.5, "Unit":"1" } }, { "Number":18, "AD":"A", "Value":{ "Value":20.6, "Unit":"1" } }, { "Number":19, "AD":"A", "Value":{ "Value":20.6, "Unit":"1" } }, { "Number":20, "AD":"A", "Value":{ "Value":20.6, "Unit":"1" } }, { "Number":21, "AD":"A", "Value":{ "Value":20.7, "Unit":"1" } }, { "Number":22, "AD":"A", "Value":{ "Value":20.7, "Unit":"1" } }, { "Number":23, "AD":"A", "Value":{ "Value":21.0, "Unit":"1" } }, { "Number":24, "AD":"A", "Value":{ "Value":21.8, "Unit":"1" } }, { "Number":25, "AD":"A", "Value":{ "Value":22.0, "Unit":"1" } }, { "Number":26, "AD":"A", "Value":{ "Value":20.7, "Unit":"1" } }], "Logging Digital":[ { "Number":1, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":3, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":7, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":8, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":9, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":10, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":11, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":12, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":13, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }]}, "Status":"OK", "Status code":0 }

**Comment by DeerMaximum** [comment]
Can you install version 1.8.0 and send me the diagnostic data of the integration?

**Comment by DeerMaximum** [comment]
Can you tell me when you installed the integration and can you see if after a restart the first query to the CMI looks like this?

`Make request to device 1 with parameters: I,O,D,Sg,Sd,St,Ss`

**Comment by peter-mul** [comment]
a) Sorry, I cannot see the installation time. The directory with the files is recreated after an update.
Because I installed the UVR16x2 in April 22 it cannot be earlier.
I is running without problems for a long time.

b) No the first query is just with Parameter I and O

9:34:20.301 DEBUG (MainThread) [ta_cmi] Update device: 1
2023-05-24 19:34:20.301 DEBUG (MainThread) [ta_cmi] Make request to device 1 with parameters: I,O

later device 1 is queried with parameters: I,O,D,Sg,Sd,St,Ss

9:46:25.092 DEBUG (MainThread) [custom_components.ta_cmi] Try to update device: 1
2023-05-24 19:46:25.093 DEBUG (MainThread) [ta_cmi] Update device: 1
2023-05-24 19:46:25.093 DEBUG (MainThread) [ta_cmi] Make request to device 1 with parameters: I,O,D,Sg,Sd,St,Ss
2023-05-24 19:47:28.411 DEBUG (MainThread) [ta_cmi] Make request to device 1 with parameters: La,Ld
2023-05-24 19:47:30.126 DEBUG (MainThread) [custom_components.ta_cmi] Wait for 61 seconds to prevent rate limiting
2023-05-24 19:48:31.128 DEBUG (MainThread) [custom_components.ta_cmi] Try to update device: 50
2023-05-24 19:48:31.128 DEBUG (MainThread) [ta_cmi] Update device: 50
2023-05-24 19:48:31.128 DEBUG (MainThread) [ta_cmi] Make request to device 50 with parameters: I,O
2023-05-24 19:48:31.367 DEBUG (MainThread) [custom_components.ta_cmi] Wait for 61 seconds to prevent rate limiting

**Comment by DeerMaximum** [comment]
Ok, in a previous version the device type was not saved yet, that's why the integration retrieves only inputs and outputs on the 1st start and creates only these entities. If you set up the integration again, the error should be fixed.

**Comment by peter-mul** [comment]
OK, I recreated the integration.
