### ISSUE TITLE
A way to read all internal Variables

### ISSUE THREAD

**Issue by henfri** [DeerMaximum/Technische-Alternative-CMI#69]
Hello Maximilian,

I have written a logic (also in python, but not in HA), that is able to read any internal Variable from UVR.
I have documented it here:
https://knx-user-forum.de/forum/supportforen/smarthome-py/1451781-technische-alternative-uvr1611-16x2-mit-cmi-werte-in-sh-py-einlesen
(it is in German; let me know if you need a translation, but your name suggests that you might know German). 

Would you have Interest to include this in HA?

Best regards,
Hendrik

**Comment by DeerMaximum** [comment]
This all looks quite experimental to me. I don't think I will add the functionality into the integration.
As far as I can see, the internal values can also be read out via CAN. So another possibility would be to read the internal values via CAN, [CoE](https://help.ta.co.at/DE/CMIHELP/coe____can_over_ethernet_.htm#) and the [CoE integration](https://github.com/DeerMaximum/Technische-Alternative-CoE).

**Comment by henfri** [comment]
Hello Maximilian,

what do you mean by "exprimental"? 
If it is the code-quality, I agree.
If it is the function, I don't. It has been working flawlessly for nine years now (https://knx-user-forum.de/forum/supportforen/smarthome-py/35834-alpha-logik-uvr1611).

The approach may not be documented by TA, but it was the TA helpdesk that told me about this possibility.

I also think that I did not explain well what values are readable for instance all the values shown in this screen are readable:
![image](https://github.com/DeerMaximum/Technische-Alternative-CMI/assets/5280909/edb939d4-987b-453e-bbb4-cc43b780cd04)

![image](https://github.com/DeerMaximum/Technische-Alternative-CMI/assets/5280909/88a121b8-9d8f-416b-9e8f-8ec240e38dbc)

That is: You can get the values that are not a physical Input/Output, but those that are results from one logic block and only passed to another one.

The whole approach is deterministic. There is an ID in the TA-Designer XML that can be found in the HTML of the visualization ("schema")

So, I do not really see what is experimental about it and I also see a significant value.

Best regards,
Hendrik

**Comment by DeerMaximum** [comment]
I find the way the data is obtained not exactly optimal, since the data is parsed from HTML.
As I see it, the data you read out can also be read out via CAN. Which is easier for the user. 

![funktion](https://github.com/DeerMaximum/Technische-Alternative-CMI/assets/43999966/c1366967-fcf3-4b27-a973-a6f1d7c1a868)

![CAN](https://github.com/DeerMaximum/Technische-Alternative-CMI/assets/43999966/a7608e98-dc67-4599-871c-93817954789f)

I want to keep the integration as lightweight as possible, and since there is already a good way to retrieve this data it is unnecessary to provide a second way.

**Comment by henfri** [comment]
Thanks.
Where do you find the view from the second screenshot?
In my CMI, I cannot select "Funktionen"
![image](https://github.com/DeerMaximum/Technische-Alternative-CMI/assets/5280909/fa63643f-a13e-4573-9349-de5ef260da6a)

Greetings,
Hendrik

**Comment by DeerMaximum** [comment]
The second screenshot is from the CAN settings of my UVR16x2. 
The page is: CAN-BUS -> CAN Analogausgänge -> Beliebiger Ausgang
