### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Ruko2010** [DeerMaximum/Technische-Alternative-CMI#70]
Sorry to misuse the issue here, but i‘m not sure how to ask a question. Is this only to read values from the c.m.i. Or can I also change the values? I have no c.m.i. Yet, but will get one if the change of values (like the warm water temperature) is possible via home assistant. 

Thanks for the help.
Christian

**Comment by DeerMaximum** [comment]
Yes you are right this integration is only to read values from the C.M.I.. But I have also developed a second one [Technische-Alternative-CoE](https://github.com/DeerMaximum/Technische-Alternative-CoE), with this one can send values via CoE to the C.M.I.. These values can then be used as values that are provided via normal CAN.
More about CoE: https://help.ta.co.at/DE/CMIHELP/coe____can_over_ethernet_.htm#

**Comment by Ruko2010** [comment]
ok, thanks. Do I need an extra device to use CoE, or does the CMI this job? For now I just have a single TA-Modul which controls my heating. If I get an CMI, I can read the values of this Module via this integration and set Values via the CoE Integration, right?
Sorry for the dump questions, but I'm completely new to HA and Technische Alternative 😃

**Comment by DeerMaximum** [comment]
No, for CoE you only need the CMI and the Home Assistant addon from the integration. You can read all data with the CoE integration and send values to the device. But i cannot tell you how your module has to be configured to work with CAN data. I'm sure you can find it in the manual.

**Comment by DeerMaximum** [comment]
stale
