### ISSUE TITLE
Read out switch position room sensor

### ISSUE THREAD

**Issue by alele-de** [DeerMaximum/Technische-Alternative-CMI#71]
Hi DeerMaximum,

is it may be possible to read out the switch position from the room sensor? At the moment this seems not to be included in a node. For me important is the "standby mode".

- Automatic mode
- Normal mode
- Lowering mode
- Standby mode

Also interesting is the target temperature from the room sensors.

Thank you and kind regards,
alele

**Comment by DeerMaximum** [comment]
If the device is not listed in the table in the readme, it is not possible to use this integration to retrieve values.
However, if the switch is a CAN device and connected to the C.M.I., you could read out the data with the [Technische-Alternative-CoE](https://github.com/DeerMaximum/Technische-Alternative-CoE) integration.

**Comment by alele-de** [comment]
Thanks for you reply. I use two RSM610 and one UVR 610 with integration Technische-Alternative-CMI  1.8.6. Do I have to install the integration with CoE additionally, or only these? Sorry for my confusion.

**Comment by alele-de** [comment]
Is it possible to reduce the fetching time under 10 min. in 'Technische-Alternative-CMI'?

**Comment by DeerMaximum** [comment]
> Thanks for you reply. I use two RSM610 and one UVR 610 with integration Technische-Alternative-CMI 1.8.6. All devices conncted to an C.M.I. Do I have to install the integration with CoE additionally, or only these? Sorry for my confusion.

Yes, you have to install the integration with CoE additionally. But you can use both integration simultaneously.

**Comment by DeerMaximum** [comment]
> Is it possible to reduce the fetching time under 10 min. in 'Technische-Alternative-CMI'?

Yes, you can reduce the fetching time to under 10 minutes but due to limits on the C.M.I. realtime fetching is not possible. If you need faster query times, please use the CoE integration, with it you can retrieve the data up to every 0.1 minute.

>Behind the configuration button of the integration is a scroll bar to move it to 4 min, but without effect.

That the slider for the update interval has no effect would be new and a bug, if this is the case please open a new ticket.

**Comment by DeerMaximum** [comment]
stale
