### ISSUE TITLE
CMI Shutdown while starting up Integration

### ISSUE THREAD

**Issue by minestrone1994** [DeerMaximum/Technische-Alternative-CMI#80]
## Version of the custom_component
v1.8.9
Running HassOs on an Intel x86 PC, newest version. 

## Describe the bug
While trying to set up the integration my CMI ist restarting itself (I have an email alert set up for this) and afterwards I only get one of the devices on my CAN-Bus (CAN I/O 45) as new device in HA, my UVR16x2 and all its sensors is not shown. Any Advice on how to fix this would be highly appreciated! Thanks! 
## Debug log

Logger: custom_components.ta_cmi
Source: custom_components/ta_cmi/config_flow.py:189
Integration: Technische Alternative C.M.I. (documentation, issues)
First occurred: 18:33:53 (1 occurrences)
Last logged: 18:33:53

Error while communicating with a device (1): Could not connect to X.X.X.X

**Comment by DeerMaximum** [comment]
Can you send me the debug logs with this configuration? This also activates the debug logs for the Python library used.

```yaml
logger:
  default: info
  logs:
    custom_components.ta_cmi: debug
    ta_cmi: debug
```

**Comment by minestrone1994** [comment]
Logs: 

 2024-01-10 12:32:51.461 DEBUG (MainThread) [ta_cmi] Receive list of nodes from C.M.I
2024-01-10 12:32:51.466 DEBUG (MainThread) [ta_cmi] Received list of nodes from C.M.I: 1;32;
2024-01-10 12:32:51.466 DEBUG (MainThread) [custom_components.ta_cmi] Sleep mode for 75 seconds to prevent rate limiting
2024-01-10 12:34:06.468 DEBUG (MainThread) [custom_components.ta_cmi] Try to fetch device type: 1
2024-01-10 12:34:06.468 DEBUG (MainThread) [ta_cmi] Make request to device 1 with parameters: I,O
2024-01-10 12:34:07.236 DEBUG (MainThread) [custom_components.ta_cmi] Sleep mode for 75 seconds to prevent rate limiting
2024-01-10 12:35:22.238 DEBUG (MainThread) [custom_components.ta_cmi] Try to fetch available device channels: 1
2024-01-10 12:35:22.239 DEBUG (MainThread) [ta_cmi] Update device: 1
2024-01-10 12:35:22.239 DEBUG (MainThread) [ta_cmi] Make request to device 1 with parameters: I,O,D,Sg,Sd,St,Ss
2024-01-10 12:36:25.411 DEBUG (MainThread) [ta_cmi] Make request to device 1 with parameters: La,Ld
2024-01-10 12:36:39.402 WARNING (MainThread) [custom_components.ta_cmi] Error while communicating with a device (1): Could not connect to 192.168.3.114
2024-01-10 12:36:39.402 DEBUG (MainThread) [custom_components.ta_cmi] Sleep mode for 75 seconds to prevent rate limiting
2024-01-10 12:37:54.404 DEBUG (MainThread) [custom_components.ta_cmi] Try to fetch device type: 32
2024-01-10 12:37:54.404 DEBUG (MainThread) [ta_cmi] Make request to device 32 with parameters: I,O
2024-01-10 12:37:54.625 DEBUG (MainThread) [custom_components.ta_cmi] Sleep mode for 75 seconds to prevent rate limiting
2024-01-10 12:39:09.626 DEBUG (MainThread) [custom_components.ta_cmi] Try to fetch available device channels: 32
2024-01-10 12:39:09.627 DEBUG (MainThread) [ta_cmi] Update device: 32
2024-01-10 12:39:09.627 DEBUG (MainThread) [ta_cmi] Make request to device 32 with parameters: I,O,D

Node 1 is the UVR16x2. Any help is highly appreciated!

**Comment by DeerMaximum** [comment]
It looks like the CMI shuts down when data is retrieved from the UVR16x2.
Can you run the query with the URL manually and see what happens?

`http://192.168.3.114/INCLUDE/api.cgi?jsonnode=1&jsonparam=I,O,D,Sg,Sd,St,Ss`

If the crash is caused by the query, you can try it with the following jsonparam combinations:

* I,O
* D
* Sg
* Sd
* St
* Ss
* La
* ,Ld

Please note that you must wait at least 1 minute after a request, otherwise the rate limit will be triggered.

**Comment by minestrone1994** [comment]
Did that just now, this is the result:
{ "Header":{ "Version":7, "Device":"87", "Timestamp":1705168829 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":53.7, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":50.0, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":56.7, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":56.5, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":56.6, "Unit":"1" } }, { "Number":7, "AD":"A", "Value":{ "Value":-6.0, "Unit":"1" } }, { "Number":8, "AD":"A", "Value":{ "Value":70.4, "Unit":"1" } }, { "Number":9, "AD":"A", "Value":{ "Value":54.4, "Unit":"1" } }, { "Number":10, "AD":"A", "Value":{ "Value":57.1, "Unit":"1" } }, { "Number":11, "AD":"A", "Value":{ "Value":57.9, "Unit":"1" } }, { "Number":12, "AD":"A", "Value":{ "Value":-6.2, "Unit":"1" } }, { "Number":13, "AD":"A", "Value":{ "Value":15.4, "Unit":"1" } }], "Outputs":[ { "Number":1, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":3, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":12, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":13, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":14, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":16, "AD":"A", "Value":{ "State":0, "Value":0.0, "Unit":"8" } }], "DL-Bus":[ { "Number":1, "AD":"A", "Value":{ "Value":19.6, "Unit":"46", "RAS":"0" } }, { "Number":2, "AD":"A", "Value":{ "Value":19.6, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":30.4, "Unit":"8" } }, { "Number":4, "AD":"A", "Value":{ "Value":23.8, "Unit":"46", "RAS":"0" } }, { "Number":5, "AD":"A", "Value":{ "Value":23.7, "Unit":"1" } }, { "Number":6, "AD":"A", "Value":{ "Value":28.1, "Unit":"8" } }, { "Number":7, "AD":"A", "Value":{ "Value":21.1, "Unit":"46", "RAS":"0" } }, { "Number":8, "AD":"A", "Value":{ "Value":21.0, "Unit":"1" } }, { "Number":9, "AD":"A", "Value":{ "Value":36.9, "Unit":"8" } }, { "Number":10, "AD":"A", "Value":{ "Value":0, "Unit":"3" } }, { "Number":11, "AD":"A", "Value":{ "Value":28.3, "Unit":"1" } }, { "Number":12, "AD":"A", "Value":{ "Value":33.7, "Unit":"1" } }], "General":[ { "Number":1, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":3, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":5, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":7, "AD":"A", "Value":{ "Value":50.16, "Unit":"21" } }, { "Number":8, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":9, "AD":"D", "Value":{ "Value":1, "Unit":"44" } }, { "Number":10, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":11, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":12, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":13, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }], "Date":[ { "Number":1, "AD":"A", "Value":{ "Value":13, "Unit":"0" } }, { "Number":2, "AD":"A", "Value":{ "Value":1, "Unit":"0" } }, { "Number":3, "AD":"A", "Value":{ "Value":24, "Unit":"0" } }, { "Number":4, "AD":"A", "Value":{ "Value":6, "Unit":"0" } }, { "Number":5, "AD":"A", "Value":{ "Value":2, "Unit":"0" } }, { "Number":6, "AD":"A", "Value":{ "Value":13, "Unit":"0" } }, { "Number":7, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":8, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":9, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":10, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }], "Time":[ { "Number":1, "AD":"A", "Value":{ "Value":15, "Unit":"4" } }, { "Number":2, "AD":"A", "Value":{ "Value":20, "Unit":"5" } }, { "Number":3, "AD":"A", "Value":{ "Value":18, "Unit":"15" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":7, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":8, "AD":"A", "Value":{ "Value":1100, "Unit":"60" } }], "Sun":[ { "Number":1, "AD":"A", "Value":{ "Value":467, "Unit":"60" } }, { "Number":2, "AD":"A", "Value":{ "Value":996, "Unit":"60" } }, { "Number":3, "AD":"A", "Value":{ "Value":0, "Unit":"5" } }, { "Number":4, "AD":"A", "Value":{ "Value":633, "Unit":"5" } }, { "Number":5, "AD":"A", "Value":{ "Value":0, "Unit":"5" } }, { "Number":6, "AD":"A", "Value":{ "Value":104, "Unit":"5" } }, { "Number":7, "AD":"A", "Value":{ "Value":-16.8, "Unit":"54" } }, { "Number":8, "AD":"A", "Value":{ "Value":256.7, "Unit":"54" } }, { "Number":9, "AD":"D", "Value":{ "Value":0, "Unit":"44" } }, { "Number":10, "AD":"A", "Value":{ "Value":731, "Unit":"60" } }]}, "Status":"OK", "Status code":0 }
there is no shutdown when I run this - but I did update the CMI to the latest version before running the above query, maybe that fixed it. Will try to update the UVR16x2 as well and then retry the integration setup. Should be done in about half an hour, will report. Thanks for your quick help!

**Comment by minestrone1994** [comment]
It works, so if anybody encounters this issue as well: update your CMI, this error is fixed in one of the last firmware Updates!
Thanks for the help!
