### ISSUE TITLE
COP-Value

### ISSUE THREAD

**Issue by Kasper027** [DeerMaximum/Technische-Alternative-CMI#81]
Hey, nice Project, it works fine.

I run a heat pump. I measure the electrical and thermal energy via M-Bus with the UVR610. This means I can calculate the COP and the annual performance factor directly in the UVR. I would like to transfer these two values to Home Assistant. Sure, I could calculate both in Home Assistant, but that would still be nice.
In order to have the values directly with Winsol, I activated/integrated them in the CAN bus logging. Is there a way to transfer these values to Home Assistant?

Many greetings, Julian

**Comment by DeerMaximum** [comment]
With the UVR610, the integration supports reading out the M-Bus values, so you could load the values into Home Assistant and calculate the COP there. 

Reading the COP directly via CAN logging is not yet supported, but you can call up the following URL and see if it returns any values. If this is the case, I can add support.

`http://CMI-IP/INCLUDE/api.cgi?jsonnode=NODE&jsonparam=I,O,La,Ld`

Under NODE, enter the CAN ID of the UVR610 and under CMI-Ip the IP of your C.M.I.

**Comment by Kasper027** [comment]
Hey @DeerMaximum 
I found my Values:

> { "Header":{ "Version":7, "Device":"91", "Timestamp":1705252141 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":65.5, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":35.3, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":126, "Unit":"3" } }, { "Number":4, "AD":"A", "Value":{ "Value":35.8, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":36.9, "Unit":"1" } }, { "Number":6, "AD":"A", "Value":{ "Value":61.8, "Unit":"1" } }], "Outputs":[ { "Number":1, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":7, "AD":"A", "Value":{ "State":1, "Value":59.6, "Unit":"8" } }, { "Number":8, "AD":"A", "Value":{ "State":1, "Value":84.0, "Unit":"8" } }, { "Number":9, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }], "Logging Analog":[ { "Number":1, "AD":"A", "Value":{ "Value":65.5, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":35.3, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":128, "Unit":"3" } }, { "Number":4, "AD":"A", "Value":{ "Value":35.8, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":36.9, "Unit":"1" } }, { "Number":6, "AD":"A", "Value":{ "Value":61.8, "Unit":"1" } }, { "Number":7, "AD":"A", "Value":{ "Value":40.5, "Unit":"1" } }, { "Number":8, "AD":"A", "Value":{ "Value":57.4, "Unit":"1" } }, **_{ "Number":10, "AD":"A", "Value":{ "Value":2.70, "Unit":"24" } }, { "Number":11, "AD":"A", "Value":{ "Value":2.42, "Unit":"24" }_** }, { "Number":12, "AD":"A", "Value":{ "Value":392.0, "Unit":"11" } }, { "Number":13, "AD":"A", "Value":{ "Value":1719.9, "Unit":"11" } }, { "Number":15, "AD":"A", "Value":{ "Value":4.43, "Unit":"10" } }, { "Number":16, "AD":"A", "Value":{ "Value":33, "Unit":"0" } }, { "Number":17, "AD":"A", "Value":{ "Value":5.82, "Unit":"10" } }, { "Number":18, "AD":"A", "Value":{ "Value":2.15, "Unit":"10" } }], "Logging Digital":[ { "Number":1, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":3, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":7, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":8, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":9, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":10, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }]}, "Status":"OK", "Status code":0 }

This two Values are the from the Can-Datalogging:

<img width="416" alt="image" src="https://github.com/DeerMaximum/Technische-Alternative-CMI/assets/35900030/76e16e3d-2f1c-4828-b379-22f5a47bc24c">


Is it possible, to get the Values into HA?

**Comment by DeerMaximum** [comment]
You should be able to call up the values in the latest version (1.9.0).

**Comment by Kasper027** [comment]
yes it works. thanks
