### ISSUE TITLE
wie macht man eine Graphen bzw. Doku auf Deutsch

### ISSUE THREAD

**Issue by Gampi65** [DeerMaximum/Technische-Alternative-CMI#82]
Hallo bin neu hier, und reiner Anwender, und shreibe zum ersten Mal,
Super Integration - tolle Arbeit,
Wird die Schnittstelle direkt vom Hersteller Technische Alternative gefördert?
Gibt es evt eine Doku auf deutsch?
Gibt es auch einen Graph- Diagramm bzw eine Statistik
Hab die Integration in Betrieb funktioniert sehr gut,
Einzige Frage: muss man wenn man einen kanal ergänzt oder ändert jedes Mal von vorne beginnen oder kann man Sensoren hinzufügen bzw ntfernen?

**Comment by DeerMaximum** [comment]
> Wird die Schnittstelle direkt vom Hersteller Technische Alternative gefördert?
Gibt es evt eine Doku auf deutsch?

Ja die API wird von Technische Alternative zu Verfügung gestellt. Die Doku findest du hier: https://wiki.ta.co.at/C.M.I._JSON-API

> Gibt es auch einen Graph- Diagramm bzw eine Statistik

Inwiefern? Du kannst die Internen Graphen von Home Assistatn benutzen oder über z.B. InfluxDB und Grafana in Kombination mit Home Assistant Graphen erstellen. Da gibts genug Anleitungen im Internet.

>Einzige Frage: muss man wenn man einen kanal ergänzt oder ändert jedes Mal von vorne beginnen oder kann man Sensoren hinzufügen bzw ntfernen?

Das kommt darauf an, wenn du bei der Einrichtung ausgewählt hast, dass alle Channel abgerufen werden sollen, dann musst du nur die Integration neuladen im die neuen Channel zu laden. Falls nicht musst du bist jetzt die Einrichtung nochmal durchführen.

**Comment by Gampi65** [comment]
Hallo,

danke für die Antwort,
ich bin Consumer und hab mich durchgewühlt so das die Integrationnun  stabil läuft bzw. Habe ich Technische Alternative und deren Produkte seit 2007 im Einsatz,
Ich meine mich zu erinnern das Winsol im Ursprung von einem Anwender kam, bzw in jüngster Vergangenheit hörte man von Bemühungen Richtung mehr Schnittstellen, KNX etc.
Deine Schnittstelle inkl dem integrierten HA Graph läuft nun seit einer guten Woche in meinem HA Netz stabil,
stehe gerne zur Verfügung sollte etwas getestet werden usw. gern helfe ich meine Beobschtungen für eine Doku etc aufzuzeichen, ansonsten tolle Ergänzung zu TA Reglern.
Danke für die Antwort, gruss Gampi

Am 15. Jänner 2024 16:15:14 MEZ schrieb DeerMaximum ***@***.***>:

**Comment by DeerMaximum** [comment]
Ich komme bei Bedarf darauf zurück
