### ISSUE TITLE
Is it possible to reduce the query interval?

### ISSUE THREAD

**Issue by linuxdep** [DeerMaximum/Technische-Alternative-CMI#97]
Hi, great that you have made an integration in HA for the CMI of TA. But what surprises me is that the data is only in HA every 5 minutes, which is a step backwards compared to my BL-NET where I could save all changes live in my Maria-DB. The analysis was then carried out with Data Logger Pro. Now my expectations of the CMI were the same, but I had hoped to be able to read out even better data. Apparently the CMI can't do that, because there is no more live data in Winsol. Or am I doing something wrong? I have set the CMI to log data every 2s.

**Comment by DeerMaximum** [comment]
The API from the C.M.I. that this integration uses, allows only one request per minute. So for 4 devices the integration needs to make 4 calls with a delay of 1 minute each. 

If you want a higher rate you could use my [other integration](https://github.com/DeerMaximum/Technische-Alternative-CoE), which works via CanOverEthernet and doesn't have these limits.

**Comment by linuxdep** [comment]
Schade das schon geschlossen wurde, schreibe jetzt mal in deutsch weiter, geht schneller. 
Auch die andere Einbindung ist ja begrenzt im Abfrageintervall. 
Ich dachte eigentlich du lädst die Daten die schon auf dem CMI geloggt werden aus und bringst diese in HA, so wie es Winsol ja auch macht. Aber mit 5min. Daten kann man ja nicht wirklich was anfangen zum Auswerten. Bei der Aussentemperatur mag das reichen, aber Reglungen von Pumpen darzustellen nicht. 
Mache ich was falsch, oder geht das so nicht wie ich das denke? Meine Versuche die Daten per Modbus bereitzustellen sind auch nicht erfolgreich. Etwas vom CMI enttäuscht bisher.

**Comment by DeerMaximum** [comment]
> Ich dachte eigentlich du lädst die Daten die schon auf dem CMI geloggt werden aus und bringst diese in HA, so wie es Winsol ja auch macht. Aber mit 5min.

Nein, über die API der CMI kann man nur die aktuellen Daten auslesen. 

> Auch die andere Einbindung ist ja begrenzt im Abfrageintervall.

Jein, über CoE werden die Daten sofort bei Änderung an den Server geschickt. Die Integration ruft diese dann in einem festgelegten Intervall vom Server ab. Da hier aber kein Rate-Limit besteht, kannst du Aktualisierungsrate auf 0,1 Minuten(6 Sekunden) stellen.

>Meine Versuche die Daten per Modbus bereitzustellen sind auch nicht erfolgreich

Bei dem Thema kann ich dir leider nicht helfen.

Ich hoffe, ich konnte dir weiterhelfen.

**Comment by linuxdep** [comment]
Danke dir, ich werde weiter Testen, was meiner alten Lösung am nächsten kommt.
